services:
  backend:
    build:
      context: .
      dockerfile: MadAbroad-Backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # These now read from your .env file
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      # This is the new bind mount. It links the ./uploads folder in your project root
      # to the /app/uploads folder inside the container.
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s

  db:
    image: mysql:8.0
    environment:
      # These also read from your .env file, ensuring they match
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      # We now use a named volume for database data. This is more robust.
      - mysql-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# Top-level declaration for our named volume.
volumes:
  mysql-volume:
